# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_items_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items_made',
            field=models.ManyToManyField(related_name='item_maker', to='item_app.Item'),
        ),
    ]
